 flowchart TB;
    B{Login}
    B --> |Credenciales correctas|D[Lobby]
    D --> E[Child List]
    D --> R[Datos usuario]
    D --> Salir
    E --> F[Child]
    F --> K[Datos medicos]
    F --> L[Progreso Tapat]