sequenceDiagram
    participant Usuario
    participant App
    participant WebService
    participant BBDD

    alt Entrada sense token
        Usuario->>App: Ingresa usuario y contraseña
        App->>WebService: Envía credenciales
        WebService->>BBDD: Consulta usuario y contraseña
        BBDD-->>WebService: Responde con resultado (válido o no)
        alt Credenciales válidas
            WebService-->>App: Devuelve token de autenticación
            App-->>Usuario: Acceso permitido
        else Credenciales inválidas
            WebService-->>App: Devuelve error de autenticación
            App-->>Usuario: Muestra mensaje de error
        end
    else Entrada amb token
        Usuario->>App: Ingresa token
        App->>WebService: Envia token
        WebService->>BBDD: Consulta token
        BBDD->>WebService: Responde con entrada permitida (token válido)
        WebService->>Usuario: Acceso permitido
    end
